# Definition of the function
signature = '''
interface Item {
  description: string;
  price: number;
  // Count of this item to purchase.
  quantity: number;
}

interface Invoice {
    count: number;
    price: number;
}

function invoice(items: Item[]): Invoice
'''
definition = '''
The function sums the prices of all items in the invoice, adding sales tax of 10%.
''''

[[test]]
definition = """
Given the items:

3 x Coffee Mug for $8.99 each
1 x Gift Card fo $50.00

Confirm that the count is 4 and price is 84.667, including the tax of 10%.

""""
